---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# utilsR

<!-- badges: start -->
<!-- badges: end -->

`utilsR` is my personal R-based useful utils in data analysis. Feel free to use it :)

## Installation

You can install the released version of utilsR the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("thereallda/utilsR")
```
## Example

```{r,warning=FALSE,message=FALSE}
library(utilsR)
```

### ggPCA

PCA plot from counts matrix

```{r}
set.seed(123)
counts_mat <- matrix(rnbinom(30000, mu=100, size=1), ncol=10)
groups <- rep(c('A','B'), each=5)
labels <- paste(rep(c('A','B'), each=5), 1:5, sep = '.')
ggPCA(counts_mat, group = groups, label = labels, vst.norm = TRUE)
```


### BetweenStatPlot

Box-violin plot comparing values between groups

```{r}
data("iris")
head(iris)
BetweenStatPlot(iris, x = 'Species', y = 'Sepal.Width', color = 'Species',
                comparisons = list(c('setosa','versicolor'), c('versicolor','virginica')))
```

### gene2goterm

Convert gene id to GO term

```{r}
# Convert gene id to GO term
gene2goterm(c("ENSMUSG00000025981", "ENSMUSG00000057363"), organism = 'mmusculus')
```

### ggVolcano

```{r}
library(DESeq2)
dds <- makeExampleDESeqDataSet(n=5000, m=4, betaSD = 5)
dds <- DESeq(dds)
res <- results(dds, contrast=c("condition","B","A"))
res.tab <- as.data.frame(res)
ggVolcano(res.tab)
```
